name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  backend:
    description: 'Select GHDL backend (mcode, llvm or gcc)'
    required: false
    default: mcode
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'index.js'
