name: 'Setup GHDL'
description: 'Easily install nightly GHDL assets in GitHub Actions workflows'
inputs:
  backend:
    description: 'Select GHDL backend (mcode, llvm or gcc)'
    required: false
    default: mcode
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: gray-dark
  icon: play