name: "test"

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:

  ubuntu:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        task: [ '', mcode, llvm, gcc ]
        version: [ 18.04, 20.04 ]
    runs-on: ubuntu-${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        backend: ${{ matrix.task }}
    - run: ghdl --version

  windows:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        task: [
          { msys: MINGW32, backend: mcode },
          { msys: MINGW64, backend: llvm }
        ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.task.msys }}
        update: true
    - uses: ./
      with:
        backend: ${{ matrix.task.backend }}
    - shell: msys2 {0}
      run: |
        ghdl --version
